### ISSUE TITLE
setting  the bot can only be used by one or more users which are authorized.

### ISSUE THREAD

**Issue by 8ty** [xeust/telespace#1]
setting  the bot can only be used by one or more users which are authorized.
add a judgment to the bot, specify talents to run the program, others do not reply.this can use telegram uid to recognise.
Prevent malicious use by others

**Comment by xeust** [comment]
I'm sorry, could you please explain the feedback a bit more in detail?

**Comment by xeust** [comment]
@8ty , there is a recent update, I believe this could address your issue.

**Comment by xeust** [comment]
going to close the issue here
