### ISSUE TITLE
What is BLACKHOLE_URL ?

### ISSUE THREAD

**Issue by mehranparazit** [xeust/telespace#10]
Hi, I configured everything even the BOT_TOKEN and OPENAI_API but in canvas settings there a BLACKHOLE_URL variable, what is that ?

Also I get this interface even after setting the variables :

hey!
one or both of your configuration variables are not set, please do the following from the telemage app's card on your deta space canvas:
click on "...", select "settings", and then "configuration".
set both the configuration variables: "OPEN_AI" and "TELEGRAM". then click "save changes".

**Comment by xeust** [comment]
Hi there @mehranparazit ,

The error you get means one of the two required fields is not setup. The BLACKHOLE_URL is an optional integration to save your generated images in https://deta.space/discovery/@mikhailsdv/black_hole-3kf
