### ISSUE TITLE
SSL certificate on deta 

### ISSUE THREAD

**Issue by jinmingteo** [xeust/telespace#2]
Hi @xeust ,

thank you for the great repository. 
I tried to replicate on deta space but was unable to pass the SSL certificate that Telegram webhook requires.

Are you able to share some tips on how you use webhook on deta platform for this app?

Thanks!

**Comment by xeust** [comment]
Hi @jinmingteo -- sorry for the late response.

Can you please provide a bit more context of the error you're getting? When you try and set the webhook, you get an error message? If so, can you please provide the error message?

**Comment by jinmingteo** [comment]
Hi @xeust, thank you for the kind assistance. I am able to set the webhook without receiving any issue from the output payload but when I tried to getWebhookInfo, i am receiving this. 

`"last_error_message":"SSL error {error:0A000086:SSL routines::certificate verify failed}", `

What I did: 
git clone your repository, edit configurations and space push..

**Comment by xeust** [comment]
Hi @jinmingteo, ok thanks for the context.

Can I ask when you visit the app on your Canvas, is there a valid certificate served?

**Comment by jinmingteo** [comment]
hey @xeust, how do i check that? 

everything should be on default setting.
I tried cloning telemage on the Space Canvas and it worked. However, i am unable to do any code-editing from the cloned Space right?

thanks!

**Comment by xeust** [comment]
Hi @jinmingteo ,

If you navigate to the app (click on it's icon) does your browser load it?

If not, can you please install a fresh copy and see if it works? https://deta.space/discovery/@max/telespace
